"""add_knowledge_base_tables

Revision ID: b4517d633649
Revises: f1ffe52667ef
Create Date: 2025-08-11 23:07:43.936820

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b4517d633649'
down_revision = 'f1ffe52667ef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_base_collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('collection_type', sa.String(), nullable=False),
    sa.Column('chroma_collection_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chroma_collection_name')
    )
    op.create_index(op.f('ix_knowledge_base_collections_id'), 'knowledge_base_collections', ['id'], unique=False)
    op.create_table('knowledge_base_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('document_type', sa.String(), nullable=False),
    sa.Column('document_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['knowledge_base_collections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_base_documents_id'), 'knowledge_base_documents', ['id'], unique=False)
    op.drop_index('ix_conversations_customer_type', table_name='conversations')
    op.drop_column('conversations', 'last_activity_at')
    op.drop_column('conversations', 'rate_limit_reset_at')
    op.drop_column('conversations', 'rate_limit_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('rate_limit_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('conversations', sa.Column('rate_limit_reset_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('conversations', sa.Column('last_activity_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_index('ix_conversations_customer_type', 'conversations', ['customer_type'], unique=False)
    op.drop_index(op.f('ix_knowledge_base_documents_id'), table_name='knowledge_base_documents')
    op.drop_table('knowledge_base_documents')
    op.drop_index(op.f('ix_knowledge_base_collections_id'), table_name='knowledge_base_collections')
    op.drop_table('knowledge_base_collections')
    # ### end Alembic commands ### 