"""add_customer_persistence_fields_to_conversations

Revision ID: f1ffe52667ef
Revises: 2da3325cf02d
Create Date: 2025-08-11 19:36:44.306611

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f1ffe52667ef'
down_revision = '2da3325cf02d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add customer persistence fields to conversations table
    op.add_column('conversations', sa.Column('customer_type', sa.VARCHAR(), server_default=sa.text("'authenticated'::character varying"), nullable=True))
    op.add_column('conversations', sa.Column('customer_identifier', sa.VARCHAR(), nullable=True))
    op.add_column('conversations', sa.Column('linked_email', sa.VARCHAR(), nullable=True))
    op.add_column('conversations', sa.Column('expires_at', postgresql.TIMESTAMP(), nullable=True))
    
    # Create indexes for better performance
    op.create_index('ix_conversations_customer_type', 'conversations', ['customer_type'], unique=False)
    op.create_index('ix_conversations_customer_identifier', 'conversations', ['customer_identifier'], unique=False)
    op.create_index('ix_conversations_linked_email', 'conversations', ['linked_email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove indexes
    op.drop_index('ix_conversations_linked_email', table_name='conversations')
    op.drop_index('ix_conversations_customer_identifier', table_name='conversations')
    op.drop_index('ix_conversations_customer_type', table_name='conversations')
    
    # Remove customer persistence fields
    op.drop_column('conversations', 'expires_at')
    op.drop_column('conversations', 'linked_email')
    op.drop_column('conversations', 'customer_identifier')
    op.drop_column('conversations', 'customer_type')
    # ### end Alembic commands ### 